### ISSUE TITLE
Validation user for his EOS or EDEN account

### ISSUE THREAD

**Issue by MystoZay** [whassa/pfe-eos-voting#6]
validate the user to confirm he has a EOS or EDEN account. Only user with these types of account should be able to create new posts to vote and to vote on existing post

**Comment by marouk10** [comment]
https://github.com/eoscostarica/eden-member-check
Maybe use a smart contract

**Comment by marouk10** [comment]
https://bloks.io/account/genesis.eden
Genesis account structure

**Comment by MystoZay** [comment]
task done by whassa
